### ISSUE TITLE
Play sound when time is up

### ISSUE THREAD

**Issue by SocksTheWolf** [SocksTheWolf/TwitchTTSUser#8]
To make it more obvious to the streamer and also the person going

**Comment by DeckardHoliday** [comment]
I assume there would be an option for users to set their own sound, but here are a few chimes I whipped up while watching you stream. Feel free to use one of them for the default if you'd like!

https://drive.google.com/drive/folders/1TIzg6DvhTVaqolUOXfSpOnVynZ0hOKMd?usp=sharing

**Comment by DeckardHoliday** [comment]
> I assume there would be an option for users to set their own sound, but here are a few chimes I whipped up while watching you stream. Feel free to use one of them for the default if you'd like!
> 
> https://drive.google.com/drive/folders/1TIzg6DvhTVaqolUOXfSpOnVynZ0hOKMd?usp=sharing

I updated this with license info. It uses a CC BY 4.0 license, so free to use/modify to your hearts content, just attribute the sound! Attribution in the readme is all that's necessary

**Comment by SocksTheWolf** [comment]
@DeckardHoliday thank you I love chimes 2 so I'm just gonna throw it into the resource object of the DLL, if someone wants to change the audio, they can also rebuild the project until I implement file pickers or something similar.
